lsm:
  func_name: linear2
  ndim: 2 ####################### 2  300 (when linear2)
model:
  affine: true
  nflow: 60 #### 20    60/40
optimizer:
  LR: 0.001 ####### 0.001  0.0001
output:
  save: true    #true
  verbose: true
parameters:
  batch_size: 2 #### 1000 o    10 l 2          50
  epochs: 1 ######## 5 70                   20
regularizer:
  LogDet: 2 ############ 1 o   50  5  1.5
